### ISSUE TITLE
Instructions For Installing SpaceVim - OFFLINE

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/Hack-SpaceVim#12]
Some people maybe have no connection to the Internet.(Yeah, a lot of people)

So, they need a post to teach them how to install SpaceVim FASTER , SAFELY and OFFLINE, including on Windows and Linux.

**Comment by Gabirel** [comment]
Finished in https://github.com/Gabirel/Hack-SpaceVim/commit/915875d48032457e8b7e6f0706e73ceea8497709

**Comment by haomeng689** [comment]
I find a spacevim package for offline installation. However, there are many tar errors when extracting the tar file. Are there any solutions?

**Comment by Gabirel** [comment]
You can still use TAR in GUI to extract it.

Or, you can pack it by yourself. After all, that version I've packed is too old to use. So I highly recommend you to pack it up. More details: (Here)[https://github.com/Gabirel/Hack-SpaceVim/blob/master/en_US/installation/installation-for-linux.md#start-to-install-2]

**Comment by TamaMcGlinn** [comment]
What about updating spacevim and plugins after installation? Ideally, we would want to:
1) Get the latest commit hashes available on the offline machine
2) Using those, generate [`git bundle`](https://git-scm.com/docs/git-bundle) files containing only the new commits, so that we have minimal file(s) to transfer to the offline machine
3) Update using these bundle files

I would imagine this should be implemented as a spacevim layer, with step 1 generating a script to be run on the online machine. Because it operates on git bundle files, it would allow updating an offline windows machine using an online linux machine or any other configuration of different OS'es.

**Comment by Gabirel** [comment]
@TamaMcGlinn 
1. Nice idea to use [`git bundle`](https://git-scm.com/docs/git-bundle) for incremental updates. This gives me a lot of thinking about it. I'll add this idea into docs later for others' reference. 
2. Currently, generating bundle files created via `git bundle` as one independent layer is almost impossible for SpaceVim. 

There are two reasons for the number`2`:
  - First, current SpaceVim(`v1.4.0`) has its self-contained, so-called `bundle` folder for managing necessary plugins. Those plugins are just bare source code without any `.git` information, which makes it impossible to do so. 
(BTW, SpaceVim manager(@wsdjeg) dislikes managing plugins via git methods. So, in the long run, I don't think it is possible for this request.)
  - Second, the plugin manager embedded in SpaceVim only has limited function, which doesn't include generating incremental bundled files for offline updates. 

Maybe for offline users, they need to consider writing scripts to maintain incremental updates.

**Comment by TamaMcGlinn** [comment]
@changyonggang I used to solve that problem simply by installing the exact some config on another computer that can visit the internet, and zipping up the `~/.vim/plugged` directory after updating, and replacing the one on the offline computer.

What I was suggesting is a more efficient way of doing that - I used to have to move gigabytes of plugins, so I would only do it every few months.
